alter table Master add primary key (playerID);
alter table Batting add primary key (playerID, yearID, stint, teamID, lgID);
alter table Pitching add primary key (playerID, yearID, stint, teamID, lgID);
alter table Fielding add primary key (playerID, yearID, stint, teamID, lgID, Pos);
alter table AllstarFull add primary key (playerID, yearID, lgID, gameID);
alter table HallOfFame add primary key (playerID, yearID, votedBy);
alter table Managers add primary key (playerID, yearID, teamID, lgID, inseason);
alter table Teams add primary key (yearID, teamID, lgID);
alter table BattingPost add primary key (playerID, yearID, teamID, lgID, round);
alter table PitchingPost add primary key (playerID, yearID, teamID, lgID, round);
alter table TeamsFranchises add primary key (franchID);
alter table FieldingOF add primary key (playerID, yearID, stint);
alter table ManagersHalf add primary key (playerID, yearID, teamID, lgID, half);
alter table TeamsHalf add primary key (yearID, teamID, lgID, half);
alter table Salaries add primary key (playerID, yearID, teamID, lgID);
alter table SeriesPost add primary key (yearID, round);
alter table AwardsManagers add primary key (playerID, awardID, yearID, lgID);
alter table AwardsPlayers add primary key (playerID, yearID, awardID, lgID);
alter table AwardsShareManagers add primary key (playerID, yearID, awardID, lgID);
alter table AwardsSharePlayers add primary key (playerID, yearID, awardID, lgID);
alter table FieldingPost add primary key (playerID, yearID, lgID, round, Pos);
alter table Appearances add primary key (playerID, yearID, teamID, lgID);
alter table Schools add primary key (schoolID);
alter table CollegePlaying add primary key (playerID, schoolID, yearID);
alter table FieldingOFsplit add primary key (playerID, yearID, lgID, stint, Pos);
alter table Parks add primary key (`park.key`);
alter table HomeGames add primary key (`park.key`, `team.key`, `year.key`, `league.key`);