alter table Master drop primary key;
alter table Batting drop primary key;
alter table Pitching drop primary key;
alter table Fielding drop primary key;
-- -- alter table AllstarFull drop primary key;
alter table HallOfFame drop primary key;
alter table Managers drop primary key;
-- alter table Teams drop primary key;
-- alter table BattingPost drop primary key;
-- alter table PitchingPost drop primary key;
-- alter table TeamsFranchises drop primary key;
-- alter table FieldingOF drop primary key;
-- alter table ManagersHalf drop primary key;
-- alter table TeamsHalf drop primary key;
-- alter table Salaries drop primary key;
-- alter table SeriesPost drop primary key;
-- alter table AwardsManagers drop primary key;
alter table AwardsPlayers drop primary key;
-- alter table AwardsShareManagers drop primary key;
-- alter table AwardsSharePlayers drop primary key;
-- alter table FieldingPost drop primary key;
-- alter table Appearances drop primary key;
-- alter table Schools drop primary key;
-- alter table CollegePlaying drop primary key;
-- alter table FieldingOFsplit drop primary key;
-- alter table Parks drop primary key;
-- alter table HomeGames drop primary key;

