alter table Batting drop foreign key Batting_ibfk_1;
-- alter table Batting drop foreign key Batting_ibfk_2;
-- alter table Batting drop key `teamID`;
alter table Pitching drop foreign key Pitching_ibfk_1;
-- alter table Pitching drop foreign key Pitching_ibfk_2;
-- alter table Pitching drop key `teamID`;
alter table Fielding drop foreign key Fielding_ibfk_1;
-- alter table Fielding drop foreign key Fielding_ibfk_2;
-- alter table Fielding drop key `teamID`;
-- alter table AllstarFull drop foreign key AllstarFull_ibfk_1;
-- alter table AllstarFull drop foreign key AllstarFull_ibfk_2;
-- alter table AllstarFull drop key `teamID`;
alter table HallOfFame drop foreign key HallOfFame_ibfk_1;
alter table Managers drop foreign key Managers_ibfk_1;
-- alter table Managers drop foreign key Managers_ibfk_2;
-- alter table Managers drop key `teamID`;
-- alter table Teams drop foreign key Teams_ibfk_1;
-- alter table BattingPost drop foreign key BattingPost_ibfk_1;
-- alter table BattingPost drop foreign key BattingPost_ibfk_2;
-- alter table BattingPost drop key `teamID`;
-- alter table PitchingPost drop foreign key PitchingPost_ibfk_1;
-- alter table PitchingPost drop foreign key PitchingPost_ibfk_2;
-- alter table PitchingPost drop key `teamID`;
-- alter table FieldingOF drop foreign key FieldingOF_ibfk_1;
-- alter table ManagersHalf drop foreign key ManagersHalf_ibfk_1;
-- alter table ManagersHalf drop foreign key ManagersHalf_ibfk_2;
-- alter table ManagersHalf drop key `teamID`;
-- alter table Salaries drop foreign key Salaries_ibfk_1;
-- alter table Salaries drop foreign key Salaries_ibfk_2;
-- alter table Salaries drop key `teamID`;
-- alter table SeriesPost drop foreign key SeriesPost_ibfk_1;
-- alter table SeriesPost drop foreign key SeriesPost_ibfk_2;
-- alter table SeriesPost drop key `teamIDwinner`;
-- alter table SeriesPost drop key `teamIDloser`;
-- alter table AwardsManagers drop foreign key AwardsManagers_ibfk_1;
alter table AwardsPlayers drop foreign key AwardsPlayers_ibfk_1;
-- alter table AwardsShareManagers drop foreign key AwardsShareManagers_ibfk_1;
-- alter table AwardsSharePlayers drop foreign key AwardsSharePlayers_ibfk_1;
-- alter table FieldingPost drop foreign key FieldingPost_ibfk_1;
-- alter table FieldingPost drop foreign key FieldingPost_ibfk_2;
-- alter table FieldingPost drop key `teamID`;
-- alter table Appearances drop foreign key Appearances_ibfk_1;
-- alter table Appearances drop foreign key Appearances_ibfk_2;
-- alter table Appearances drop key `teamID`;
-- alter table CollegePlaying drop foreign key CollegePlaying_ibfk_1;
-- alter table CollegePlaying drop foreign key CollegePlaying_ibfk_2;
-- alter table FieldingOFsplit drop foreign key FieldingOFsplit_ibfk_1;
-- alter table FieldingOFsplit drop foreign key FieldingOFsplit_ibfk_2;
-- alter table FieldingOFsplit drop key `teamID`;
-- alter table HomeGames drop foreign key HomeGames_ibfk_1;
-- alter table HomeGames drop foreign key HomeGames_ibfk_2;

-- alter table Teams drop index teamID_idx;